### ISSUE TITLE
Get-Avatars call fails

### ISSUE THREAD

**Issue by BulcziProgramming** [TheMich4/season-summary#61]
When loading the page, a failure is shown.

According to the console, get-avatars call fails.

_GET https://api.season-summary.dyczkowski.dev/v2/get-avatars?ids=697669,219245,190594 net::ERR_CERT_COMMON_NAME_INVALID_

**Comment by BulcziProgramming** [comment]
The failure of that http call remains a fact, but that seems to not be a reason for driver data loading failure. After clearing local storage from last visited profiles (which ID's are passed in the call above) the data loading problem persists.

It simply prints: _Failed to get data for <driver_id_here>_

**Comment by TheMich4** [comment]
Hello, thanks for reporting, the backend was down for few days, all should be working now.

**Comment by BulcziProgramming** [comment]
Works on my end :) TY for bringing it up again <3
